### ISSUE TITLE
hanging autopep8.py hangs emacs

### ISSUE THREAD

**Issue by starenka** [paetzke/py-autopep8.el#10]
I know this is not py-autopep8 issue, but it is really annoying. Imagine you have a file (f.e one w/ huge dict definition) which effectively kills autopep8 (or make it really busy for couple minutes). While this is happening, the whole is editor is frozen and can't be worked with. Could this issue be solved async processing?

It's super annoying especially when you have autopep8 on save hook on.

**Comment by paetzke** [comment]
I know what you mean. Right now, I don't know how to fix this. I have to do some research on this topic.

**Comment by myint** [comment]
Have you tried limiting maximum the number of passes (`--pep8-passes`)?

**Comment by starenka** [comment]
@myint kudos!

**Comment by paetzke** [comment]
I will add this to a FAQ. Thanks!
