### ISSUE TITLE
Inability to add agressiveness levels higher than 1

### ISSUE THREAD

**Issue by DavidSnider** [paetzke/py-autopep8.el#12]
No matter what I try setting the py-autopep8-options variable to, I either get 1 of 2 outcomes. Either I do something along the lines of `(setq py-autopep8-options '("-a"))` and get an aggresssiveness level lower than I want or do something along the lines of `(setq py-autopep8-options '("-a -a))` and get an error. Is this an issue with my understanding of the py-autopep8-options variable?

**Comment by paetzke** [comment]
Hi,

you are trying to use "-a" multiple times? Could you try this: 
```lisp
(setq py-autopep8-options '("-a" "-a"))
```

Sorry that it took me so long to answer.

**Comment by DavidSnider** [comment]
Sorry for taking so long as well. That did the trick, thanks!
