### ISSUE TITLE
kill ring is modified when py-autopep8-enable-on-save hook is triggered

### ISSUE THREAD

**Issue by cjac** [paetzke/py-autopep8.el#19]
Modified ~/.emacs to include

(require 'py-autopep8.el)
(add-hook 'python-mode-hook 'py-autopep8-enable-on-save)

After saving, a number of elements have been removed from the kill ring.

code in use is

https://raw.githubusercontent.com/paetzke/py-autopep8.el/575ca51c928e6aaf01650901bce3df1122a11a4c/py-autopep8.el

**Comment by pronobis** [comment]
Could this pul request be merged? This is a very annoying problem...

**Comment by cjac** [comment]
Where's the "I hear that!" button?

**Comment by pronobis** [comment]
This fix is working well, and it should be enough to merge the pull request. Is autopep8 maintained still?
