### ISSUE TITLE
avoiding ^M when using py-autopep8 on Windows

### ISSUE THREAD

**Issue by benstroud** [paetzke/py-autopep8.el#8]
Using py-autopep8 on Windows:

test.py (saved with DOS-style EOL, but same results when saving as UNIX EOL)
```


import os, os.path
```

Becomes the following after M-x py-autopep8:

```
^M
^M
import os^M
import os.path^M
```

Is there a way to avoid the extra ^M being added? When running autopep8 from cmdline I don't get the extra characters. Thanks

**Comment by MortalCatalyst** [comment]
I have this on windows7 64 bit latest emacs 24 running emacs using https://github.com/purcell/emacs.d
This was  the only alteration to that  default configuration.

**Comment by paetzke** [comment]
Could you try this branch? https://github.com/paetzke/py-autopep8.el/tree/fix-encoding

**Comment by paetzke** [comment]
Patch is merged
